### ISSUE TITLE
Delete the display of the opt values when the instance is manual or aleatoire

### ISSUE THREAD

**Issue by Lamia-Mihoubi** [Lamia-Mihoubi/BPP_Solver#15]
![Annotation 2020-06-13 191318](https://user-images.githubusercontent.com/29714883/84576121-9d1e1600-adb2-11ea-9693-1a3d8d7d55ed.png)

**Comment by Lamia-Mihoubi** [comment]
same for random instances

**Comment by yasmine9** [comment]
i prefer that we delete that header for both first and second page 
we just keep the opt values in the scholl page

**Comment by yasmine9** [comment]
add opt val and ecart en % for scholl (for both backend and front)

**Comment by yasmine9** [comment]
fixed
