### ISSUE TITLE
Increse the float precision of the execution time when displaying it (rahou int so yji 0s x))

### ISSUE THREAD

**Issue by Lamia-Mihoubi** [Lamia-Mihoubi/BPP_Solver#16]
![Annotation 2020-06-13 191318](https://user-images.githubusercontent.com/29714883/84576171-f8e89f00-adb2-11ea-9c3a-06b9f9cac822.png)

**Comment by Lamia-Mihoubi** [comment]
Do the same for the rest of the algorithms' results display too.

**Comment by yasmine9** [comment]
It’s not an int , les autres algo affichent le temps d’exec avec la virgule 
A aucun moment we’re transforming it to int 
So that’s the precision of python floats par défaut 
I’ll search if we can increase it
