### ISSUE TITLE
Remove the popup alert that shows up when instance is generated

### ISSUE THREAD

**Issue by Lamia-Mihoubi** [Lamia-Mihoubi/BPP_Solver#17]
![Annotation 2020-06-13 192505](https://user-images.githubusercontent.com/29714883/84576324-326dda00-adb4-11ea-9724-c0f69b62cf7a.png)

**Comment by Lamia-Mihoubi** [comment]
now that the alert is removed, the user doesn't feel any difference once the instance is geenrated it's easy to think that nothing happened.

**Comment by yasmine9** [comment]
![dialog](https://user-images.githubusercontent.com/36101876/84602817-e5583980-ae81-11ea-8272-561ff8bc12c2.PNG)
