### ISSUE TITLE
Random instance display takes up too much space uselessly

### ISSUE THREAD

**Issue by Lamia-Mihoubi** [Lamia-Mihoubi/BPP_Solver#18]
![Annotation 2020-06-13 192758](https://user-images.githubusercontent.com/29714883/84576364-82e53780-adb4-11ea-8c3c-972fbf96cdac.png)

**Comment by yasmine9** [comment]
yeah, but we should show the geenrated objets 
maybe we search for another component to represent the list ? 
or using just a string like the "Show Resultats page"?

**Comment by Lamia-Mihoubi** [comment]
I'd rather use a better display then a simple string, but between a string and this I prefer a string.
